import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavFull from './NavBar/Components/NavFull'
import MobileNav from './NavBar/Modals/MobileNav'
import { ThemeProvider } from '@/components/context/ThemeProvider'
import { ModeToggle } from '@/components/context/ToogleButton'
import { Button } from '@/components/ui/button'
import Provider from '@/components/context/Provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen mx-auto justify-center items-center overflow-hidden  flex flex-col bg-gray-100 
          dark:bg-gray-900">
        <Provider>
          <div className='   '>
            <NavFull />
            <main className="flex flex-col flex-1 max-w-6xl w-full  ">
              {children}
            </main>
            <MobileNav />
          </div>
        </Provider>
      </body>
    </html>
  )
}
